version: '3.8'

services:
  php:
    build: .
    volumes:
      - app:/var/www/html
      - uploads:/var/www/html/web/app/uploads
      - languages:/var/www/html/web/app/languages
    expose:
      - "9000"
    environment:
      - DB_NAME=bedrock
      - DB_USER=bedrock
      - DB_PASSWORD=bedrock
      - DB_HOST=db

  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - app:/var/www/html
      - languages:/var/www/html/web/app/languages
      - uploads:/var/www/html/web/app/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bedrock
      MYSQL_USER: bedrock
      MYSQL_PASSWORD: bedrock

volumes:
  db_data:
